---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: observability
type: Opaque
stringData:
  placeholder: mock-for-local-testing
---
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
  namespace: networking
type: Opaque
stringData:
  api-token: mock-cloudflare-token-for-local-testing
---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: mock-cloudflare-token-for-local-testing
