apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: kube-prometheus-stack
spec:
  project: observability
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  sources:
  - repoURL: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
    targetRevision: 87.10.1
    helm:
      valueFiles:
      - $values/kubernetes/apps/observability/kube-prometheus-stack/app/kube-prometheus-stack-values.yaml
  - repoURL: git@github.com:dxas90/seed.git
    targetRevision: main
    ref: values
