apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- argocd/autoscaling-project.yaml
- argocd/cert-manager-project.yaml
- argocd/kube-system-project.yaml
- argocd/networking-project.yaml
- argocd/observability-project.yaml
- argocd/security-project.yaml
- kubernetes/apps/external-secrets/external-secrets/app/external-secrets-application.yaml
- kubernetes/apps/istio-system/istio/app/istio-base-application.yaml
- kubernetes/apps/istio-system/istio/app/istio-cni-application.yaml
- kubernetes/apps/istio-system/istio/app/istiod-application.yaml
- kubernetes/apps/istio-system/istio/app/ztunnel-application.yaml
- kubernetes/apps/istio-system/istio/install-istio-gateway-application.yaml
- kubernetes/apps/keda/keda-operator/app/keda-application.yaml
- kubernetes/apps/keda/keda-add-ons-http/app/keda-add-ons-http-application.yaml
- kubernetes/apps/kube-system/reloader/app/reloader-application.yaml
- kubernetes/apps/kube-system/coredns/app/coredns-application.yaml
- kubernetes/apps/networking/external-dns/app/external-dns-application.yaml
- kubernetes/apps/observability/alertmanager/app/alertmanager-application.yaml
- kubernetes/apps/observability/alloy/app/alloy-application.yaml
- kubernetes/apps/observability/gatus/app/gatus-application.yaml
- kubernetes/apps/observability/grafana/app/grafana-operator-application.yaml
- kubernetes/apps/observability/grafana/install-grafana-instance-application.yaml
- kubernetes/apps/observability/kube-prometheus-stack/app/kube-prometheus-stack-application.yaml
- kubernetes/apps/observability/kube-prometheus-stack/install-kube-prometheus-stack-config-application.yaml
- kubernetes/apps/observability/loki/app/loki-application.yaml
- kubernetes/apps/observability/node-exporter/app/node-exporter-application.yaml
- kubernetes/apps/observability/tempo/app/tempo-application.yaml
- kubernetes/apps/cert-manager/cert-manager/install-cluster-apps-cert-manager-issuers-application.yaml
- kubernetes/apps/cert-manager/cert-manager/install-cluster-apps-cert-manager-certificates-application.yaml
- clusters/aws/staging-v2/apps/external-secrets/external-secrets/application.yaml
