[tools]
python = { version='3', virtualenv='.venv' }
uv = "latest"

[settings]
experimental = true
python.uv_venv_auto = true

[env]
# Use the project name derived from the current directory
PROJECT_NAME = "{{ config_root | basename }}"
PATH = "{{ env.HOME }}/.local/bin:{{ env.PATH }}"

# Automatic virtualenv activation
_.python.venv = { path = ".venv", create = true, python_create_args = ["--without-pip", "--copies"], uv_create_args = ["--system-site-packages"] }
LC_ALL = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[hooks]
enter = "git init -q ; git submodule update --recursive --remote"
