apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.1.0
spec:
  project: observability
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana-operator
    targetRevision: 5.24.0
    helm:
      valueFiles:
      - $values/kubernetes/apps/observability/grafana/app/grafana-operator-values.yaml
  - repoURL: https://github.com/dxas90/seed
    targetRevision: main
    ref: values
  ignoreDifferences:
  - group: '*'
    kind: '*'
    jsonPointers:
    - /spec/template/metadata/creationTimestamp
  - group: ''
    kind: Service
    jsonPointers:
    - /spec/clusterIP
    - /spec/clusterIPs
  - group: ''
    kind: ServiceAccount
    jsonPointers:
    - /secrets
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/preserveUnknownFields
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    jsonPointers:
    - /rules
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jsonPointers:
    - /webhooks
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
    - /webhooks
