apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.1.0
spec:
  project: observability
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  sources:
  - repoURL: oci://ghcr.io/grafana/helm-charts/grafana-operator
    targetRevision: 5.24.0
    helm:
      valueFiles:
      - $values/kubernetes/apps/observability/grafana/app/grafana-operator-values.yaml
  - repoURL: git@github.com:dxas90/seed.git
    targetRevision: main
    ref: values
