---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "cert-manager-cloudflare-secret"
  namespace: cert-manager
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-ssm-secretsmanager
    kind: ClusterSecretStore
  target:
    name: "cert-manager-secret"
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: api-token
      remoteRef:
        key: "/seed/infrastructure/cloudflare/api-token"
