fullnameOverride: reloader
reloader:
  deployment:
    replicas: 1
  enableHA: true
  readOnlyRootFileSystem: true
  reloadStrategy: annotations
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
