fullnameOverride: node-exporter
hostNetwork: false
image:
  registry: quay.io
  repository: prometheus/node-exporter
prometheus:
  monitor:
    enabled: true
    jobLabel: app.kubernetes.io/instance
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: kubernetes_node
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: nodename
    - action: replace
      regex: (.*)
      replacement: $1.example.com:9100
      sourceLabels:
      - kubernetes_node
      targetLabel: instance
resources:
  limits:
    memory: 64M
  requests:
    cpu: 23m
    memory: 64M
