apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cert-manager
  namespace: argocd
spec:
  description: cert-manager infrastructure components
  sourceRepos:
  - '*'
  destinations:
  - server: '*'
    namespace: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
