---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-ssm-paramstore
  labels:
    app.kubernetes.io/managed-by: flux
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets

# cluster/namespace/resource/name

# /seed-staging/staging/secret/persona-api-secret
# /seed-staging/staging/secret/turnstile-web-secret
# /seed-staging/staging/secret/twilio_phone_number
