apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-apps-cert-manager-issuers
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  source:
    repoURL: https://github.com/dxas90/seed
    targetRevision: main
    path: kubernetes/apps/cert-manager/cert-manager/issuers
    directory:
      recurse: true
