apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-apps-cert-manager-certificates
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  source:
    repoURL: https://github.com/dxas90/seed
    targetRevision: main
    path: kubernetes/apps/cert-manager/cert-manager/certificates
    kustomize: {}
  ignoreDifferences:
  - group: '*'
    kind: '*'
    jsonPointers:
    - /spec/template/metadata/creationTimestamp
  - group: ''
    kind: Service
    jsonPointers:
    - /spec/clusterIP
    - /spec/clusterIPs
  - group: ''
    kind: ServiceAccount
    jsonPointers:
    - /secrets
