persistence:
  enabled: true
  size: 10Gi
service:
  ports:
  - name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: tempo
    port: 3200
    protocol: TCP
    targetPort: 3200
serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
tempo:
  compactor:
    compaction:
      block_retention: 24h
  ingester:
    max_block_duration: 5m
  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://kube-prometheus-stack-prometheus.observability.svc:9090/api/v1/write
    processor:
      local_blocks:
        flush_to_storage: true
      service_graphs: {}
      span_metrics: {}
    storage:
      path: /var/tempo/metrics
    traces_storage:
      path: /var/tempo/generator/wal
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      interval: 30s
      scrapeTimeout: 10s
  overrides:
    defaults:
      metrics_generator:
        processors:
          - local-blocks
          - service-graphs
          - span-metrics
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  reportingEnabled: false
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  retention: 24h
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
