apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-instance
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: grafana-instance
spec:
  project: observability
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  source:
    repoURL: git@github.com:dxas90/seed.git
    targetRevision: main
    path: kubernetes/apps/observability/grafana/instance
    directory:
      recurse: true
