apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/custom-part-of: external-secrets
    app.kubernetes.io/version: 3.5.7
spec:
  project: security
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
  sources:
  - repoURL: https://charts.external-secrets.io
    targetRevision: 2.7.0
    chart: external-secrets
    helm:
      valueFiles:
      - $values/kubernetes/apps/external-secrets/external-secrets/app/external-secrets-values.yaml
  - repoURL: https://github.com/dxas90/seed
    targetRevision: main
    ref: values
