---
certController:
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 150m
      memory: 128Mi
installCRDs: true
podLabels:
  app.kubernetes.io/app: external-secrets
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi
serviceAccount:
  annotations: {}
serviceMonitor:
  enabled: true
webhook:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 150m
      memory: 128Mi
