apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: istio
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: networking
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
  sources:
  - repoURL: https://istio-release.storage.googleapis.com/charts
    chart: cni
    targetRevision: 1.26.1
    helm:
      valueFiles:
      - $values/kubernetes/apps/istio-system/istio/app/istio-cni-values.yaml
  - repoURL: https://github.com/dxas90/seed
    targetRevision: main
    ref: values
  ignoreDifferences:
  - group: '*'
    kind: '*'
    jsonPointers:
    - /spec/template/metadata/creationTimestamp
  - group: ''
    kind: Service
    jsonPointers:
    - /spec/clusterIP
    - /spec/clusterIPs
  - group: ''
    kind: ServiceAccount
    jsonPointers:
    - /secrets
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    jsonPointers:
    - /rules
  - group: apps
    kind: DaemonSet
    jsonPointers:
    - /spec/revisionHistoryLimit
    - /spec/template/spec/containers/0/env/0/valueFrom/fieldRef/apiVersion
    - /spec/template/spec/containers/0/env/5/valueFrom/resourceFieldRef/divisor
    - /spec/template/spec/containers/0/env/6/valueFrom/resourceFieldRef/divisor
    - /spec/template/spec/containers/0/env/7/valueFrom/fieldRef/apiVersion
    - /spec/template/spec/containers/0/env/8/valueFrom/fieldRef/apiVersion
    - /spec/template/spec/containers/0/imagePullPolicy
    - /spec/template/spec/containers/0/readinessProbe/failureThreshold
    - /spec/template/spec/containers/0/readinessProbe/httpGet/scheme
    - /spec/template/spec/containers/0/readinessProbe/periodSeconds
    - /spec/template/spec/containers/0/readinessProbe/successThreshold
    - /spec/template/spec/containers/0/readinessProbe/timeoutSeconds
    - /spec/template/spec/containers/0/terminationMessagePath
    - /spec/template/spec/containers/0/terminationMessagePolicy
    - /spec/template/spec/dnsPolicy
    - /spec/template/spec/restartPolicy
    - /spec/template/spec/schedulerName
    - /spec/template/spec/securityContext
    - /spec/template/spec/serviceAccount
    - /spec/template/spec/volumes/0/hostPath/type
    - /spec/template/spec/volumes/3/hostPath/type
    - /spec/template/spec/volumes/4/hostPath/type
    - /spec/updateStrategy/rollingUpdate/maxSurge
    jqPathExpressions:
    - .spec.template.spec.containers[].resources
    - .spec.template.spec.initContainers[]?.resources
    - .metadata.annotations
