apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ztunnel
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: istio
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: networking
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
  sources:
  - repoURL: https://istio-release.storage.googleapis.com/charts
    chart: ztunnel
    targetRevision: 1.26.1
    helm:
      valueFiles:
      - $values/kubernetes/apps/istio-system/istio/app/ztunnel-values.yaml
  - repoURL: https://github.com/dxas90/seed
    targetRevision: main
    ref: values
  ignoreDifferences:
  - group: '*'
    kind: '*'
    jsonPointers:
    - /spec/template/metadata/creationTimestamp
  - group: ''
    kind: Service
    jsonPointers:
    - /spec/clusterIP
    - /spec/clusterIPs
  - group: ''
    kind: ServiceAccount
    jsonPointers:
    - /secrets
